feat: Sprint 15
alex-pergushev/java-shareit pull request #6
Opened 2022-10-05 17:49 UTC by alex-pergushev

2022-10-06 07:07 UTC, kukolev commented on src/main/java/ru/practicum/shareit/requests/service/ItemRequestServiceImpl.java
> +    private void checkingPageParameters(int from, int size) {
Нарушение кодстайла: Название метода лучше начинать с глагола, обозначающего действие над аргументами или над классом, которому принадлежит метод. Так назначение метода будет понятно сразу из названия. Нужно поправить.

2022-10-06 07:08 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private void checkingPageParameters(int from, int size) {
Нарушение кодстайла: Название метода лучше начинать с глагола, обозначающего действие над аргументами или над классом, которому принадлежит метод. Так назначение метода будет понятно сразу из названия. Нужно поправить.

2022-10-06 07:09 UTC, kukolev commented on src/test/java/ru/practicum/shareit/datajpatests/BookingTests.java
> +    void findAllByBookerIdAndStartAfter() {
Этот тест нужно разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Хороший юнит тест состоит из трех блоков кода:

1. Подготовка данных для теста
2. Вызов тестируемого метода
3. Проверка результатов

Важно, чтобы п.2 выполнялся однократно - так будет проще понять что пошло не так, если один или несколько тестов упадут.

Подробнее о хороших практиках юнит-тестирования можно прочитать тут:  https://www.baeldung.com/java-unit-testing-best-practices

Аналогичных проблем в тестах много, нужно поправить все подобные тесты во всех классах.

2022-10-06 07:09 UTC, kukolev commented on src/test/java/ru/practicum/shareit/datajpatests/BookingTests.java
> +        Page<Booking> bookings = repository.findAllByBookerIdAndStartBeforeAndEndAfter(userBooker.getId(), LocalDateTime.now().plusMinutes(5), LocalDateTime.now().plusMinutes(5), Pageable.unpaged());
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-10-06 07:09 UTC, kukolev commented on src/test/java/ru/practicum/shareit/datajpatests/BookingTests.java
> +        bookings = repository.findAllByBookerIdAndStartAfter(userBooker.getId(), LocalDateTime.now().minusHours(3), Pageable.unpaged());
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-10-06 07:10 UTC, kukolev commented on src/test/java/ru/practicum/shareit/datajpatests/BookingTests.java
> +        Page<Booking> bookings = repository.findAllByBookerIdAndStatus(userBooker.getId(), BookingStatus.REJECTED, Pageable.unpaged());
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-10-06 07:10 UTC, kukolev commented on src/test/java/ru/practicum/shareit/datajpatests/BookingTests.java
> +        Page<Booking> bookings = repository.findAllByItemIdInAndStartAfter(userOwner.getId(), LocalDateTime.now(), Pageable.unpaged());
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-10-06 07:10 UTC, kukolev commented on src/test/java/ru/practicum/shareit/datajpatests/BookingTests.java
> +        bookings = repository.findAllByItemIdInAndStartAfter(userOwner.getId(), LocalDateTime.now().minusHours(3), Pageable.unpaged());
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-10-06 07:11 UTC, kukolev commented on src/test/java/ru/practicum/shareit/datajpatests/BookingTests.java
> +        Page<Booking> bookings = repository.findAllByItemIdInAndEndBefore(userOwner.getId(), LocalDateTime.now(), Pageable.unpaged());
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-10-06 07:11 UTC, kukolev commented on src/test/java/ru/practicum/shareit/datajpatests/BookingTests.java
> +        bookings = repository.findAllByItemIdInAndEndBefore(userOwner.getId(), LocalDateTime.now().plusHours(3), Pageable.unpaged());
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-10-06 07:11 UTC, kukolev commented on src/test/java/ru/practicum/shareit/datajpatests/BookingTests.java
> +        Page<Booking> bookings = repository.findAllByItemIdInAndStatus(userOwner.getId(), BookingStatus.REJECTED, Pageable.unpaged());
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-10-06 07:12 UTC, kukolev commented on src/test/java/ru/practicum/shareit/dto/ItemRequestTests.java
> +    JacksonTester<ItemRequestDto> jacksonTester;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-10-06 07:13 UTC, kukolev commented on src/test/java/ru/practicum/shareit/rest/RequestTests.java
> +    ItemRequestService requestService;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-10-06 07:14 UTC, kukolev commented on src/test/java/ru/practicum/shareit/unettests/ItemRequestTests.java
> +    ItemRequestRepository mockItemRequestRepository;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-10-06 16:59 UTC, alex-pergushev commented on src/test/java/ru/practicum/shareit/datajpatests/BookingTests.java
> +    void findAllByBookerIdAndStartAfter() {
тесты для слоя репозиториев сделаны в соответствии с рекомендациями приведенными в ТЗ: "Работа с аннотацией @DataJpaTest не рассматривалась подробно в уроке, поэтому вам предстоит изучить пример самостоятельно, [перейдя по ссылке](https://howtodoinjava.com/spring-boot2/testing/datajpatest-annotation/)."

2022-10-07 14:25 UTC, kukolev requested changes

2022-10-07 14:25 UTC, kukolev commented on src/test/java/ru/practicum/shareit/datajpatests/BookingTests.java
> +    void findAllByBookerIdAndEndBefore() {
Не исправлено замечание https://github.com/alex-pergushev/java-shareit/pull/6#discussion_r988626092
Нужно разбить тест на два.

2022-10-07 14:25 UTC, kukolev commented on src/test/java/ru/practicum/shareit/datajpatests/BookingTests.java
> +    void findAllByBookerIdAndStartAfter() {
Не исправлено замечание https://github.com/alex-pergushev/java-shareit/pull/6#discussion_r988626092
Нужно разбить тест на два.

2022-10-07 14:25 UTC, kukolev commented on src/test/java/ru/practicum/shareit/datajpatests/BookingTests.java
> +    void findAllByBookerIdAndStatus() {
Не исправлено замечание https://github.com/alex-pergushev/java-shareit/pull/6#discussion_r988626092
Нужно разбить тест на два.

2022-10-07 14:25 UTC, kukolev commented on src/test/java/ru/practicum/shareit/datajpatests/BookingTests.java
> +    void findAllByItemIdIn() {
Не исправлено замечание https://github.com/alex-pergushev/java-shareit/pull/6#discussion_r988626092
Нужно разбить тест на два.

2022-10-07 14:25 UTC, kukolev commented on src/test/java/ru/practicum/shareit/datajpatests/BookingTests.java
> +    void findAllByItemIdInAndEndBefore() {
Не исправлено замечание https://github.com/alex-pergushev/java-shareit/pull/6#discussion_r988626092
Нужно разбить тест на два.

2022-10-07 14:25 UTC, kukolev commented on src/test/java/ru/practicum/shareit/datajpatests/BookingTests.java
> +    void findAllByItemIdInAndStartAfter() {
Не исправлено замечание https://github.com/alex-pergushev/java-shareit/pull/6#discussion_r988626092
Нужно разбить тест на два.

2022-10-07 14:25 UTC, kukolev commented on src/test/java/ru/practicum/shareit/datajpatests/BookingTests.java
> +    void findAllByItemIdInAndStatus() {
Не исправлено замечание https://github.com/alex-pergushev/java-shareit/pull/6#discussion_r988626092
Нужно разбить тест на два.

2022-10-07 14:25 UTC, kukolev commented on src/test/java/ru/practicum/shareit/integrationtests/BookingTests.java
> +    void findAllById() {
Не исправлено замечание https://github.com/alex-pergushev/java-shareit/pull/6#discussion_r988626092
Нужно разбить тест на шесть тестов.

2022-10-07 14:25 UTC, kukolev commented on src/test/java/ru/practicum/shareit/integrationtests/BookingTests.java
> +    void findAllByOwner() {
Не исправлено замечание https://github.com/alex-pergushev/java-shareit/pull/6#discussion_r988626092
Нужно разбить тест на шесть тестов.

2022-10-07 14:25 UTC, kukolev commented on src/test/java/ru/practicum/shareit/unettests/ItemRequestTests.java
> +    void getAllFailParametersPage() {
Не исправлено замечание https://github.com/alex-pergushev/java-shareit/pull/6#discussion_r988626092
Нужно разбить тест на два.

2022-10-07 14:25 UTC, kukolev commented on src/test/java/ru/practicum/shareit/unettests/ItemRequestTests.java
> +    void mapperToRequestDto() {
Не исправлено замечание https://github.com/alex-pergushev/java-shareit/pull/6#discussion_r988626092
Нужно разбить тест на два.

2022-10-07 14:25 UTC, kukolev commented on src/test/java/ru/practicum/shareit/unettests/ItemTest.java
> +    void searchPageParametersFail() {
Не исправлено замечание https://github.com/alex-pergushev/java-shareit/pull/6#discussion_r988626092
Нужно разбить тест на два.

2022-10-09 16:02 UTC, kukolev requested changes

2022-10-09 16:02 UTC, kukolev commented on src/test/java/ru/practicum/shareit/unettests/ItemRequestTests.java
> +        final ValidationException exception = Assertions.assertThrows(
Не исправлено замечание https://github.com/alex-pergushev/java-shareit/pull/6#discussion_r988626092
Нужно разбить тест на два.

2022-10-09 16:02 UTC, kukolev commented on src/test/java/ru/practicum/shareit/unettests/ItemTest.java
> +    void findAllByIdPageParametersFail() {
Не исправлено замечание https://github.com/alex-pergushev/java-shareit/pull/6#discussion_r988626092
Нужно разбить тест на два.

2022-10-09 19:25 UTC, kukolev approved these changes

2022-10-10 12:56 UTC, merged