feat: Sprint 16
alex-pergushev/java-shareit pull request #7
Opened 2022-10-11 07:20 UTC by alex-pergushev

2022-10-11 16:35 UTC, kukolev requested changes
Не выполнено требование ТЗ: Нужно из shareId-server вынести в shareIt-gateway всю логику валидации входных данных — кроме той, которая требует работы с БД.

Класс ItemServiceImpl содержит метод валидации - checkPageParameters
В классе UserServiceImpl есть валидация в методе update

2022-10-11 16:35 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                              @PositiveOrZero @RequestParam(name = "from", defaultValue = "0") Integer from,
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-10-11 16:35 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                 @PositiveOrZero @RequestParam(name = "from", defaultValue = "0") Integer from,
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-10-11 16:35 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                 @Positive @RequestParam(name = "size", defaultValue = "10") Integer size) {
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-10-11 16:35 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                              @Positive @RequestParam(name = "size", defaultValue = "10") Integer size) {
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-10-11 16:35 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            throw new ValidationException("Время окончания бронирования должно быть позже времени начала бронирования.");
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-10-11 16:35 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +    private <T> ResponseEntity<Object> makeAndSendRequest(HttpMethod method, String path, Long userId, @Nullable Map<String, Object> parameters, @Nullable T body) {
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-10-11 16:35 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (userId == 0) {
Бизнес-логика должна быть реализована в сервисах, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

Аналогично нужно поправить ниже.

2022-10-11 16:35 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/user/UserController.java
> +        if (user.getName() == null || user.getName().isBlank()) {
Бизнес-логика должна быть реализована в сервисах, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

Аналогично нужно поправить ниже.

2022-10-11 16:35 UTC, kukolev commented on gateway/src/main/resources/application.properties
> +#logging.level.org.apache.http=DEBUG
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-10-11 16:35 UTC, kukolev commented on pom.xml
> +		<relativePath/> <!-- lookup parent from repository -->
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-10-11 17:42 UTC, alex-pergushev commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                              @PositiveOrZero @RequestParam(name = "from", defaultValue = "0") Integer from,
done

2022-10-11 17:45 UTC, alex-pergushev commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                 @PositiveOrZero @RequestParam(name = "from", defaultValue = "0") Integer from,
done

2022-10-11 17:47 UTC, alex-pergushev commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            throw new ValidationException("Время окончания бронирования должно быть позже времени начала бронирования.");
done

2022-10-11 17:52 UTC, alex-pergushev commented on gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +    private <T> ResponseEntity<Object> makeAndSendRequest(HttpMethod method, String path, Long userId, @Nullable Map<String, Object> parameters, @Nullable T body) {
done

2022-10-11 17:53 UTC, alex-pergushev commented on gateway/src/main/resources/application.properties
> +#logging.level.org.apache.http=DEBUG
done

2022-10-11 17:57 UTC, alex-pergushev commented on pom.xml
> +		<relativePath/> <!-- lookup parent from repository -->
done

2022-10-13 11:53 UTC, alex-pergushev commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (userId == 0) {
Считаю валидацию входных данных можно оставить в контроллерах. Другое решение потребует значительного рефакторинга кода, что не требует ТЗ.

2022-10-15 08:19 UTC, kukolev requested changes

2022-10-15 08:19 UTC, kukolev commented on server/src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        //log.debug("Создание нового пользователя с идентификатором: {}", user.getId());
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-10-15 08:25 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (userId == 0) {
Валидация в контроллерах в принципе допустима, главное, чтобы валидация была в одном месте. Минус валидации  контроллерах в том, что если интерфейсов в приложении будет несколько, то такую валидацию нужно будет дублировать в каждом интерфейсе.

Также на мой взгляд лучше вывести валидацию в отдельный метод.

2022-10-16 09:37 UTC, alex-pergushev commented on server/src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> -        if (bookingDto.getStart().isAfter(bookingDto.getEnd())) {
Done

2022-10-16 09:38 UTC, alex-pergushev commented on server/src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        //log.debug("Создание нового пользователя с идентификатором: {}", user.getId());
Done

2022-10-16 09:44 UTC, alex-pergushev commented on server/src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        //log.debug("Создание нового пользователя с идентификатором: {}", user.getId());
Done

2022-10-16 16:37 UTC, kukolev approved these changes

2022-10-17 09:11 UTC, merged